/* Quiet Signal: editorial modernism, warm paper, ink hierarchy, and restrained vermilion. */
import { useEffect, useMemo, useState } from "react";
import { ArrowUpRight, ChevronDown, Download, Github, Linkedin, Mail, Menu, Pencil, Plus, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";

type Project = { id: string; title: string; category: string; description: string; year: string; role: string; tools: string[]; image?: string; link?: string; sections: { title: string; body: string }[] };
type Certification = { id: string; name: string; issuer: string; note?: string };
type SkillGroup = { category: string; skills: string[] };

const initialProjects: Project[] = [
  { id: "interview", title: "AI Mock Interview System", category: "AI", description: "A final year project exploring how an AI-assisted interview flow can help candidates practise with structure and reflection.", year: "Final year project", role: "Student project", tools: ["AI", "Prompt Engineering", "Python"], image: "/manus-storage/quiet-signal-workflow_234c129b.jpg", sections: [{ title: "Overview", body: "An editable project record. Add your problem, approach, implementation notes, results, and learnings here as the project evolves." }, { title: "My contribution", body: "Document your responsibilities, collaboration, and the decisions you made." }] },
  { id: "patient", title: "Patient Management System", category: "Python", description: "A practical information-management project focused on organising patient records and everyday workflows.", year: "Academic project", role: "Student project", tools: ["Python", "Data", "Technology"], image: "/manus-storage/quiet-signal-data_7138f9ef.jpg", sections: [{ title: "Overview", body: "Add the context, objective, system flow, and implementation details for this project." }] },
  { id: "gen-ai", title: "Generative AI Mini Project", category: "Generative AI", description: "An exploration of generative AI concepts through a focused mini project and practical experimentation.", year: "Mini project", role: "Student project", tools: ["Generative AI", "Prompt Engineering"], image: "/manus-storage/quiet-signal-hero_ee42c15a.jpg", sections: [{ title: "Overview", body: "Add the experiment, prompts, workflow, outputs, and learnings when ready." }] },
  { id: "cosmos", title: "Cosmos App Redesign", category: "UX/UI", description: "A supporting design project exploring a clearer, more intentional experience for a digital product.", year: "Design project", role: "Design contributor", tools: ["Figma", "UX/UI"], sections: [{ title: "Overview", body: "Add the problem, research, flow, design decisions, and final solution here." }] },
];
const initialCerts: Certification[] = ["IBM Chatbot Certification — IBM", "IBM SkillsBuild (CB0101EN) — IBM", "Technical Poster Presentation — 2nd Prize", "Deloitte Technology Job Simulation — Deloitte", "Python Internship Certificate", "Microsoft UX Design Professional Certificate", "Google UX Design Foundations", "Animation & Graphics Certification"].map((x, i) => { const [name, issuer] = x.split(" — "); return { id: String(i), name, issuer: issuer || "Achievement", note: i === 2 ? "Competition achievement" : undefined }; });
const initialSkills: SkillGroup[] = [
  { category: "AI & Automation", skills: ["Prompt Engineering", "Context Engineering", "AI Automation", "Retrieval-Augmented Generation (RAG)", "AI Agents", "n8n", "Claude AI", "ChatGPT", "Google Gemini"] },
  { category: "Programming", skills: ["Python", "HTML", "JSON"] },
  { category: "Data & Analytics", skills: ["SQL", "Excel", "Power BI"] },
  { category: "Development Tools", skills: ["Visual Studio Code", "GitHub", "Postman"] },
  { category: "Design & Creative", skills: ["Figma", "Canva", "Adobe Photoshop", "CorelDRAW"] },
  { category: "Professional Skills", skills: ["Communication", "Leadership", "Team Collaboration", "Event Coordination"] },
];

function useStored<T>(key: string, fallback: T) { const [value, setValue] = useState<T>(() => { try { return JSON.parse(localStorage.getItem(key) || "null") || fallback; } catch { return fallback; } }); useEffect(() => localStorage.setItem(key, JSON.stringify(value)), [key, value]); return [value, setValue] as const; }

export default function Home() {
  const [projects, setProjects] = useStored<Project[]>("yfa-projects", initialProjects);
  const [certs, setCerts] = useStored<Certification[]>("yfa-certs", initialCerts);
  const [skills, setSkills] = useStored<SkillGroup[]>("yfa-skills", initialSkills);
  const [filter, setFilter] = useState("All"); const [open, setOpen] = useState<Project | null>(null); const [editor, setEditor] = useState(false); const [mobileNav, setMobileNav] = useState(false);
  const categories = useMemo(() => ["All", ...Array.from(new Set(projects.map(p => p.category)))], [projects]);
  const visible = filter === "All" ? projects : projects.filter(p => p.category === filter);
  const addProject = () => { const next: Project = { id: crypto.randomUUID(), title: "Untitled project", category: "Other", description: "Add a short description.", year: "", role: "", tools: [], sections: [{ title: "Overview", body: "Add project context here." }] }; setProjects([...projects, next]); setOpen(next); };
  const addCert = () => setCerts([...certs, { id: crypto.randomUUID(), name: "New certification", issuer: "Issuing organization", note: "" }]);
  const updateProject = (updated: Project) => { setProjects(projects.map(p => p.id === updated.id ? updated : p)); setOpen(updated); };
  return <div className="site-shell"><aside className="index-rail" aria-label="Portfolio index"><div className="rail-brand">YFA</div><div className="rail-line"/><div className="rail-status">OPEN TO<br/>LEARNING<br/>+ BUILDING</div><div className="rail-count">2026 / 01</div></aside>
    <header className="topbar"><a className="brand" href="#home"><img src="/manus-storage/quiet-signal-logo_19be56c0.png" alt="" /><span>YFA / PORTFOLIO</span></a><button className="mobile-toggle" onClick={() => setMobileNav(!mobileNav)} aria-label="Toggle navigation"><Menu size={20}/></button><nav className={mobileNav ? "nav open" : "nav"}>{["Work", "Certifications", "About", "Contact"].map(x => <a key={x} href={`#${x.toLowerCase()}`} onClick={() => setMobileNav(false)}>{x}</a>)}<a className="resume-link" href="#contact"><Download size={14}/> Resume</a></nav></header>
    <main id="home"><section className="hero"><div className="hero-copy"><p className="eyebrow">AI / AUTOMATION / DATA / TECHNOLOGY</p><h1>AI &amp; Automation<br/><em>Enthusiast.</em></h1><p className="hero-lede">I’m Yasmin Fathima A, a B.Sc. Information Technology student interested in building practical systems with AI, automation, data, and emerging technology.</p><div className="actions"><a className="button primary" href="#work">View my work <ArrowUpRight size={16}/></a><a className="button secondary" href="#contact">Contact me <Mail size={16}/></a></div></div><div className="hero-note"><span className="signal-dot"/><p>Currently learning<br/><strong>how ideas become<br/>repeatable workflows.</strong></p><span className="hero-index">01 — 05 / INDEXED</span></div></section>
      <section className="ticker" aria-label="Areas of interest"><span>AREAS OF INTEREST</span><strong>Artificial Intelligence</strong><strong>Workflow Automation</strong><strong>Prompt Engineering</strong><strong>Data &amp; Analytics</strong></section>
      <section id="work" className="section work-section"><div className="section-heading"><div><p className="eyebrow">02 / SELECTED WORK</p><h2>Records of<br/><em>practice.</em></h2></div><p className="section-intro">A working index of academic projects, experiments, and practical problem solving. Open a record to inspect the thinking, tools, and next steps behind it.</p></div><div className="filter-row"><div className="filters">{categories.map(c => <button className={filter === c ? "filter active" : "filter"} onClick={() => setFilter(c)} key={c}>{c}</button>)}</div><button className="text-action" onClick={addProject}><Plus size={15}/> Add project</button></div><div className="project-list">{visible.map((p, i) => <article className="project-row" key={p.id} onClick={() => setOpen(p)}><div className="project-num">0{i + 1}</div><div className="project-preview">{p.image ? <img src={p.image} alt=""/> : <div className="placeholder-art"><span>PROJECT<br/>IMAGE</span></div>}</div><div className="project-info"><div className="meta-line"><span>{p.category}</span><span>{p.year}</span></div><h3>{p.title}</h3><p>{p.description}</p><div className="tag-row">{p.tools.map(t => <span key={t}>{t}</span>)}</div></div><ArrowUpRight className="row-arrow" size={22}/></article>)}</div></section>
      <section id="certifications" className="section cert-section"><div className="section-heading compact"><div><p className="eyebrow">03 / CREDENTIALS</p><h2>Proof of<br/><em>practice.</em></h2></div><button className="text-action" onClick={addCert}><Plus size={15}/> Add certification</button></div><div className="cert-list">{certs.map((c, i) => <div className="cert-row" key={c.id}><span className="cert-index">{String(i + 1).padStart(2, "0")}</span><div><strong>{c.name}</strong><span>{c.issuer}{c.note ? ` · ${c.note}` : ""}</span></div><Pencil size={15}/></div>)}</div></section>
      <section id="about" className="section about-section"><div className="section-heading compact"><div><p className="eyebrow">04 / ABOUT</p><h2>A curious mind for<br/><em>useful systems.</em></h2></div><p className="section-intro">I’m a B.Sc. Information Technology student with a strong interest in AI Automation, Prompt Engineering, and Workflow Automation. I’m interested in building AI-powered solutions while continuously learning emerging technologies.</p></div><div className="about-grid"><div><span className="big-initial">Y</span><p>I also serve as a Placement President, coordinating communication between students, faculty, and the Placement Cell around placement-related initiatives.</p></div><div className="skill-groups">{skills.map(g => <div className="skill-group" key={g.category}><h4>{g.category}</h4><div>{g.skills.map(s => <span key={s}>{s}</span>)}</div></div>)}</div></div><div className="involvement"><p className="eyebrow">LEADERSHIP / INVOLVEMENT</p><div className="involvement-grid"><div><strong>Placement President</strong><span>Student representative · coordination</span></div><div><strong>Technical Symposium Volunteer</strong><span>Event management · participant coordination</span></div><div><strong>Social Media Marketing</strong><span>Promotional content · affiliate strategies</span></div></div></div></section>
      <section id="contact" className="contact"><div><p className="eyebrow">05 / CONTACT</p><h2>Make the next<br/><em>signal.</em></h2></div><div className="contact-details"><a href="mailto:yasminfathima281@gmail.com"><Mail size={17}/> yasminfathima281@gmail.com</a><a href="https://www.linkedin.com/in/yasmin-fathima-26a255352" target="_blank"><Linkedin size={17}/> LinkedIn</a><a href="https://github.com/yasminfathima05" target="_blank"><Github size={17}/> GitHub</a><a href="https://www.behance.net/yasminfathima05" target="_blank"><ArrowUpRight size={17}/> Behance</a></div></section>
    </main><footer><span>© Yasmin Fathima A</span><span>Built with curiosity / maintained with intention</span><button onClick={() => setEditor(true)}><Pencil size={13}/> Edit portfolio</button></footer>
    <Dialog open={!!open} onOpenChange={(v) => !v && setOpen(null)}><DialogContent className="project-dialog"><DialogHeader><DialogTitle>{open?.title}</DialogTitle></DialogHeader>{open && <ProjectEditor project={open} onChange={updateProject} onDelete={() => { setProjects(projects.filter(p => p.id !== open.id)); setOpen(null); }}/>}</DialogContent></Dialog>
    <Dialog open={editor} onOpenChange={setEditor}><DialogContent className="editor-dialog"><DialogHeader><DialogTitle>Portfolio content</DialogTitle></DialogHeader><p className="dialog-note">Your content is stored in this browser. Use this panel to grow the portfolio without changing its visual structure.</p><Label>About note</Label><Textarea defaultValue="I’m a B.Sc. Information Technology student with a strong interest in AI Automation, Prompt Engineering, and Workflow Automation." className="mb-4"/><div className="editor-stat"><span>{projects.length} projects</span><span>{certs.length} certifications</span><span>{skills.reduce((a, g) => a + g.skills.length, 0)} skills</span></div><Button onClick={() => { setEditor(false); addProject(); }}><Plus size={16}/> Add project</Button></DialogContent></Dialog>
  </div>;
}

function ProjectEditor({ project, onChange, onDelete }: { project: Project; onChange: (p: Project) => void; onDelete: () => void }) { const [draft, setDraft] = useState(project); const set = (k: keyof Project, v: any) => setDraft({ ...draft, [k]: v }); const save = () => onChange(draft); const addSection = () => set("sections", [...draft.sections, { title: "New section", body: "Add content here." }]); return <div className="project-editor"><div className="field-grid"><div><Label>Title</Label><Input value={draft.title} onChange={e => set("title", e.target.value)}/></div><div><Label>Category</Label><Input value={draft.category} onChange={e => set("category", e.target.value)}/></div><div><Label>Date / stage</Label><Input value={draft.year} onChange={e => set("year", e.target.value)}/></div><div><Label>My role</Label><Input value={draft.role} onChange={e => set("role", e.target.value)}/></div></div><Label>Short description</Label><Textarea value={draft.description} onChange={e => set("description", e.target.value)}/><Label>Tools (comma separated)</Label><Input value={draft.tools.join(", ")} onChange={e => set("tools", e.target.value.split(",").map(x => x.trim()).filter(Boolean))}/><div className="editor-section-head"><Label>Editable sections</Label><button className="text-action" onClick={addSection}><Plus size={14}/> Add section</button></div>{draft.sections.map((s, i) => <div className="editable-section" key={i}><div><Input value={s.title} onChange={e => { const a = [...draft.sections]; a[i] = { ...s, title: e.target.value }; set("sections", a); }}/><Textarea value={s.body} onChange={e => { const a = [...draft.sections]; a[i] = { ...s, body: e.target.value }; set("sections", a); }}/></div><button onClick={() => set("sections", draft.sections.filter((_, j) => j !== i))} aria-label="Delete section"><X size={16}/></button></div>)}<div className="dialog-actions"><Button variant="outline" onClick={onDelete}>Delete</Button><Button onClick={save}>Save changes</Button></div></div>; }
